databases:
  - name: bookstore_db
    databaseName: online_bookstore
    user: bookstore_user
    plan: free

services:
  - type: web
    name: online-bookstore
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: bookstore_db
          property: connectionString
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
